import { useState } from 'react';
import { Calendar, Clock, MapPin, Film, Utensils, Sparkles, User, Star } from 'lucide-react';
import { eventos, type Evento } from '@/data/content';

const categoriaIcon: Record<string, typeof Film> = { Cinema: Film, Gastronomia: Utensils, Festival: Sparkles, Cultura: Star };
const categoriaCor: Record<string, string> = { Cinema: 'bg-violet-100 text-violet-700', Gastronomia: 'bg-amber-100 text-amber-700', Festival: 'bg-fuchsia-100 text-fuchsia-700', Cultura: 'bg-emerald-100 text-emerald-700' };

export default function Agenda() {
  const [filtro, setFiltro] = useState<string>('Todos');
  const categorias = ['Todos', ...new Set(eventos.map((e) => e.categoria))];
  const lista = filtro === 'Todos' ? eventos : eventos.filter((e) => e.categoria === filtro);
  return <section id="agenda" className="py-20 md:py-28 bg-gradient-to-b from-white to-purple-50/50"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center max-w-2xl mx-auto mb-12"><span className="inline-block px-4 py-1.5 rounded-full bg-purple-100 text-purple-700 text-sm font-semibold mb-4">Programação</span><h2 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-purple-950 tracking-tight">São Paulo Food Film Fest</h2><p className="mt-4 text-lg text-purple-700/70 leading-relaxed">Cinema, gastronomia e cultura alimentar em sete dias de programação gratuita. Todas as sessões e atividades são de entrada franca.</p></div><div className="flex flex-wrap justify-center gap-2 mb-10">{categorias.map((cat) => <button key={cat} onClick={() => setFiltro(cat)} className={`px-4 py-2 rounded-full text-sm font-semibold transition-all ${filtro === cat ? 'bg-purple-600 text-white shadow-lg shadow-purple-500/30' : 'bg-white text-purple-700 border border-purple-200 hover:border-purple-400'}`}>{cat}</button>)}</div><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">{lista.map((evento) => <EventCard key={evento.id} evento={evento} />)}</div></div></section>;
}

function EventCard({ evento }: { evento: Evento }) {
  const Icon = categoriaIcon[evento.categoria] ?? Calendar;
  const cor = categoriaCor[evento.categoria] ?? 'bg-purple-100 text-purple-700';
  return <article className="group bg-white rounded-2xl overflow-hidden shadow-md shadow-purple-900/5 hover:shadow-xl hover:shadow-purple-500/10 transition-all hover:-translate-y-1 border border-purple-100/60"><div className="relative h-52 overflow-hidden"><img src={evento.imagem} alt={evento.titulo} loading="lazy" decoding="async" referrerPolicy="no-referrer" className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500" /><div className="absolute inset-0 bg-gradient-to-t from-purple-950/70 via-transparent to-transparent" />{evento.destaque && <span className="absolute top-3 right-3 px-3 py-1 rounded-full bg-fuchsia-500 text-white text-xs font-bold shadow-lg">Destaque</span>}<span className={`absolute top-3 left-3 inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold ${cor}`}><Icon className="w-3.5 h-3.5" />{evento.categoria}</span></div><div className="p-5"><h3 className="text-lg font-bold text-purple-950 leading-snug">{evento.titulo}</h3><p className="mt-2 text-sm text-purple-700/70 leading-relaxed line-clamp-2">{evento.descricao}</p><div className="mt-4 space-y-1.5 text-sm text-purple-800/80"><div className="flex items-center gap-2"><Calendar className="w-4 h-4 text-purple-500" /><span>{evento.data}</span></div><div className="flex items-center gap-2"><Clock className="w-4 h-4 text-purple-500" /><span>{evento.horario}</span></div><div className="flex items-center gap-2"><MapPin className="w-4 h-4 text-purple-500" /><span>{evento.local}</span></div>{evento.direcao && <div className="flex items-center gap-2"><User className="w-4 h-4 text-purple-500" /><span>Dir. {evento.direcao}</span></div>}{evento.duracao && <div className="flex items-center gap-2"><Film className="w-4 h-4 text-purple-500" /><span>{evento.duracao}</span></div>}{evento.classificacao && <div className="flex items-center gap-2"><span className="inline-flex items-center justify-center w-4 h-4 rounded border border-purple-300 text-[10px] font-bold text-purple-500">{evento.classificacao === 'Livre' ? 'L' : evento.classificacao.replace(' anos', '')}</span><span>Classificação {evento.classificacao}</span></div>}</div><div className="mt-4 pt-4 border-t border-purple-100"><span className="inline-block px-3 py-1 rounded-lg bg-emerald-50 text-emerald-700 text-xs font-bold">Entrada gratuita</span></div></div></article>;
}
